theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
L = ":buffer-next"
H = ":buffer-previous"

[keys.normal.space]
c = ":buffer-close"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"